debug: true
server:
  port: 8888
  address: 127.0.0.1
upload:
  pictures:
    uploadPath: file:./pictures
    anonymousPicture: classpath:/static/images/anonymous.png
spring:
  thymeleaf:
    cache: false
  mvc:
    locale: zh
  messages:
    cache-seconds: 0
  http:
    multipart:
      maxFileSize: 1MB
  social:
    twitter:
      appId:
      appSecret: