debug: true
server:
  port: 8888
#  address: 192.168.1.34
spring:
  thymeleaf:
    cache: false
  mvc:
    locale: zh
  messages:
    cache-seconds: 0
logging:
  level:
    org:
      springframework:
        web: DEBUG